import Head from 'next/head';

import { Header } from '../components/Header';
import { Main } from '../components/Main/index';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Calculadora de Horas de Relógio de Ponto</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='shortcut icon' href='favicon.ico' type='image/x-icon' />
				<link rel='icon' href='favicon.ico' type='image/x-icon' />
			</Head>

			<Header />
			<Main />
		</div>
	);
}
