import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Calculadora de Relógio de Ponto</title>
				<meta name='description' content='Generated by create next app' />
				<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <link rel="icon" href="favicon.ico" type="image/x-icon" />
			</Head>

			<main>
        <h1>Hello World</h1>
			</main>
		</div>
	);
}
